### ISSUE TITLE
Show user's current profile picture on the Edit Profile page

### ISSUE THREAD

**Issue by nullbitx8** [blocksoapp/monorepo#34]
**Current Behavior**
User cannot see their current pfp on Edit Profile page

**Expected Behavior**
User should see their current pfp on the Edit Profile page

**Comment by alexdavalosgit** [comment]
opened branch called iss_34 to track issue

**Comment by alexdavalosgit** [comment]
added currentpfp component and adding success messages on edit profile form

**Comment by alexdavalosgit** [comment]
todo: make profile component (pfp, bio) a reusable component

**Comment by nullbitx8** [comment]
Sweet! Squaanchaaay!

**Comment by alexdavalosgit** [comment]
**Adding:**
- Make profile component (pfp, bio) a reusable component.
- Separate profile state and formProfileData state.

**Comment by alexdavalosgit** [comment]
iss_34 has been merged into main branch
