### ISSUE TITLE
Show User 3 options for picking their profile pic

### ISSUE THREAD

**Issue by nullbitx8** [blocksoapp/monorepo#40]
**Current Behavior**
User can upload an image or select an NFT they own for their profile pic.

**Expected Behavior**
User should be able to select 1 of 3 options for their profile pic:
 1. Use their ENS avatar
 2. Use an NFT they own
 3. Upload or drag/drop an image from their device

User should see a preview of whichever option they choose.

**Comment by alexdavalosgit** [comment]
User should be able to either:

    -See a preview of the NFT or file uploaded and receive a message urging them to submit form to update pfp changes.
    -Automatically update their PFP when selecting a file or NFT they own.
